### ISSUE TITLE
ExampleCloudScript.js ReferenceError: handlers is not defined

### ISSUE THREAD

**Issue by CC-Celia** [PlayFab/SdkTestingCloudScript#1]
When I download the project and run it in VS2017, the console has an error: ReferenceError: handlers is not defined. Does it for testing cloudScript? What I want to do is Writting and Debuging CloudScript then upload to PlayFab CloudScript. What can I do next?

**Comment by pgilmorepf** [comment]
"handlers" is defined here:
https://github.com/PlayFab/SdkTestingCloudScript/blob/master/Scripts/typings/PlayFab/CloudScript.d.ts#L2

We had a separate issue with handlers for a bit where we made the function-assignment syntax a little more strict.  However, that shouldn't be related to the issue you're seeing.

All I can say is "try again", and make sure you have the node.js package checked when you run the vs2017 installer.
