### ISSUE TITLE
Proposed update to CloudScript.d.ts.

### ISSUE THREAD

**Issue by DM-John** [PlayFab/SdkTestingCloudScript#2]
At line: 3235 of CloudScript.d.ts, I'd like to propose the following change to the UpdateUserInventoryItemDataRequest object:

```
-        Data?: { [key: string]: string },
+        Data?: { [key: string]: string | null },
```

This will allow keys with null values to be provided, which will delete those entries from the ItemInstance.CustomData.

There is probably other opportunities for a similar change (e.g., UpdateUserDataRequest), but I have successfully tested this change with the ```server.UpdateUserInventoryItemCustomData()``` call.

**Comment by pgilmorepf** [comment]
Oh, interesting.  I'm surprised that null isn't an automatic choice of a string value.
I can fix that one in the generator actually, and it'll come out correct in almost all places.

**Comment by pgilmorepf** [comment]
Resolved:
https://github.com/PlayFab/SDKGenerator/commit/84aef7a8695b8a4fa58f0ac72fff400657107e13
It will be live in the next release (probably a few weeks).
