### ISSUE TITLE
Inclusion in DefinitelyTyped

### ISSUE THREAD

**Issue by nopol10** [PlayFab/SdkTestingCloudScript#4]
Hi, are there any plans for Cloudscript's types to be added to DefinitelyTyped so that we can easily include it into projects through a package manager?

**Comment by pgilmorepf** [comment]
Thanks for your suggestion!
I'm going to close this issue, because it isn't strictly an "issue" but a request.

I highly recommend you re-post this request to our forums:
https://community.playfab.com/index.html
A different team monitors the forums, and can drive suggestions like this.

Thanks!
